### ISSUE TITLE
TypeError in Recommendation Summary

### ISSUE THREAD

**Issue by klauern** [linkedin/JTune#10]
In running JTune with a JVM that I've previously adjusted heap and size values based on a prior run, I get this:

	* Reading gc.log file... done. Scanned 3007 lines in 0.0014 seconds.

	Meta:
	~~~~~
	Sample Time:    13m50s (830 seconds)
	System Uptime:  52d1h
	CPU Uptime:     104d2h
	Proc Uptime:    27m15s
	Proc Usertime:  11m59s (0.01%)
	Proc Systime:   30s (0.00%)
	Proc RSS:       3.83G
	Proc VSize:     5.16G
	Proc # Threads: 183

	YG Allocation Rates*:
	~~~~~~~~~~~~~~~~~~~~~
	per sec (min/mean/max):       2.85M/s     160.04M/s     512.28M/s
	per day (min/mean/max):     240.86G/d      13.19T/d      42.21T/d

	OG Promotion Rates:
	~~~~~~~~~~~~~~~~~~~
	per sec (min/mean/max):      52.96K/s      50.73M/s     114.85M/s
	per hr (min/mean/max):      186.20M/h     178.33G/h     403.76G/h

	Survivor Death Rates:
	~~~~~~~~~~~~~~~~~~~~~
	Lengths (min/mean/max): 0/1.5/11
	Death Rate Breakdown:
	   Age 1:  0.0% / 33.2% / 100.0% / 66.8% (min/mean/max/cuml alive %)
	   Age 2: -0.0% /  9.3% / 89.3% / 60.6% (min/mean/max/cuml alive %)
	   Age 3:  0.0% /  0.6% / 23.5% / 60.3% (min/mean/max/cuml alive %)
	   Age 4:  0.0% /  0.5% / 23.4% / 60.0% (min/mean/max/cuml alive %)
	   Age 5:  0.0% /  0.6% / 99.6% / 59.7% (min/mean/max/cuml alive %)
	   Age 6:  0.0% /  0.5% / 81.6% / 59.4% (min/mean/max/cuml alive %)
	   Age 7: -0.0% /  0.3% / 94.9% / 59.1% (min/mean/max/cuml alive %)
	   Age 8:  0.0% /  0.1% / 15.3% / 59.1% (min/mean/max/cuml alive %)
	   Age 9:  0.0% /  0.0% /  8.7% / 59.1% (min/mean/max/cuml alive %)
	   Age 10:  0.0% /  0.1% / 30.2% / 59.0% (min/mean/max/cuml alive %)
	   Age 11: -0.0% /  0.1% / 12.3% / 58.9% (min/mean/max/cuml alive %)
	   Age 12:  0.0% /  0.2% / 45.0% / 58.9% (min/mean/max/cuml alive %)
	   Age 13:  0.0% /  0.0% /  1.2% / 58.9% (min/mean/max/cuml alive %)
	   Age 14:  0.0% /  0.0% / 16.0% / 58.8% (min/mean/max/cuml alive %)

	GC Information:
	~~~~~~~~~~~~~~~
	YGC/FGC Count: 469/12 (Rate: 33.90/min, 0.87/min)

	GC Load (since JVM start): 7.37%
	Sample Period GC Load:     7.45%

	CMS Sweep Times: 3.382s /  4.366s /  4.982s / 0.66 (min/mean/max/stdev)
	YGC Times:       0ms / 130ms / 705ms / 102.68 (min/mean/max/stdev)
	FGC Times:       19ms / 47ms / 108ms / 23.44 (min/mean/max/stdev)
	Agg. YGC Time:   61306ms
	Agg. FGC Time:   568ms

	Est. Time Between FGCs (min/mean/max):        17h25m       1m3s        28s
	Est. OG Size for 1 FGC/hr (min/mean/max):    186.20M    178.33G    403.76G

	Overall JVM Efficiency Score*: 92.545%

	Current JVM Configuration:
	~~~~~~~~~~~~~~~~~~~~~~~~~~
			  NewSize: 172M
			  OldSize: 5.19M
		SurvivorRatio: 1
	 MinHeapFreeRatio: 40
	 MaxHeapFreeRatio: 70
		  MaxHeapSize: 3.34G
			 PermSize: 240M
			 NewRatio: 2

	Recommendation Summary:
	~~~~~~~~~~~~~~~~~~~~~~~
	Error in atexit._run_exitfuncs:
	Traceback (most recent call last):
	  File "/usr/lib64/python2.6/atexit.py", line 24, in _run_exitfuncs
		func(*targs, **kargs)
	  File "jtune/jtune.py", line 1756, in _at_exit
		optimized_for_ygcs_rate)
	  File "jtune/jtune.py", line 752, in _run_analysis
		proc_details)
	  File "jtune/jtune.py", line 1029, in _show_recommendations
		adj_ng_size)
	  File "jtune/jtune.py", line 873, in _get_survivor_info
		survivor_ratio, reduce_k((max_tenuring_size - adj_ng_size) / 1024)),
	  File "jtune/jtune.py", line 418, in reduce_k
		return reduce_k(size / Decimal("1024.0"), precision=precision,
	TypeError: unsupported operand type(s) for /: 'float' and 'Decimal'
	Error in sys.exitfunc:
	Traceback (most recent call last):
	  File "/usr/lib64/python2.6/atexit.py", line 24, in _run_exitfuncs
		func(*targs, **kargs)
	  File "jtune/jtune.py", line 1756, in _at_exit
		optimized_for_ygcs_rate)
	  File "jtune/jtune.py", line 752, in _run_analysis
		proc_details)
	  File "jtune/jtune.py", line 1029, in _show_recommendations
		adj_ng_size)
	  File "jtune/jtune.py", line 873, in _get_survivor_info
		survivor_ratio, reduce_k((max_tenuring_size - adj_ng_size) / 1024)),
	  File "jtune/jtune.py", line 418, in reduce_k
		return reduce_k(size / Decimal("1024.0"), precision=precision,
	TypeError: unsupported operand type(s) for /: 'float' and 'Decimal'

**Comment by ericbullen** [comment]
I just pushed a fix that should resolve this. Try it out, and let me know if it works for you.

**Comment by klauern** [comment]
I will do just that.  This error has happened somewhat infrequently, so I may wait a few days before giving the thumbs up.  Thank you for the quick response.

**Comment by ericbullen** [comment]
I'll go ahead and close the ticket as I believe I fixed it. If not,  you can create another one, or reopen this one. Cheers.
