### ISSUE TITLE
Is it possible to pipe output to another tool in Unix?

### ISSUE THREAD

**Issue by klauern** [linkedin/JTune#11]
So one of the things that I'm doing is trying to run a number of JTune's against a bunch of our different environments and apps.  One thing I wanted to do was have it email me the results automatically.  I currently set up a `screen` session to get JTune running, and then check in periodically to see if it completed.

My next thought was to try piping the output to a file, and then calling `mailx` on it, but it seems that at least with naive understanding of Unix, `Ctrl-C` seems to break how these pipe commands will work.

For instance, in the below use, `Ctrl-C` just outputs `^C`, and calling it again seems to cause an expection in the `tee` app.  I see similar errors with things like `mail`, etc., or anything that I want to pipe (`|`) or have run after it completes (`&&`):

```sh
[user@host gc]$ python jtune.py -s 7 -p 49023 | tee jtune-Thing-49023.txt
^C^Cclose failed in file object destructor:
Error in sys.excepthook:

Original exception was:
```

I guess my first thought is whether it's possible to just have it start on it's merry way immediately when I call `JTune` instead of having to kick it off with `Ctrl-C` every time?  I would then be able to do something more along the lines of:

```sh
sleep 300 && python jtune --immediately -s 7 -p 49023 | tee jtune-Output-49023.txt
```

But this really could boil down to some missing knowledge of process control and the shell prompt that I'm overlooking.  In any event, I would love some advice on how to accomplish this.

**Comment by ericbullen** [comment]
That should work. JTune can take a few seconds to start, but that's because it's trying to connect to the jvm via jmap. I'd recommend you use '-f 3' instead of '-f 7' b/c you'll have enough for jtune to make the full suggestions. As for your issues w/ pipes, jtune works like any other command, so if piping isn't working for you, it's not jtune. Sorry I can't help you more here.
