### ISSUE TITLE
Issue finding GC log file with log file rotation

### ISSUE THREAD

**Issue by kilink** [linkedin/JTune#16]
JTune cannot locate the GC log file when log file rotation is enabled with the -XX:+UseGCLogFileRotation flag. This happens when running on a Java 8 VM (1.8.0_66), and probably some later versions of Java 7. Support for GCLogFileRotation was added in PR #5.

The issue is that the current GC log is now suffixed with ".current". This change was discussed in [JDK-7164841](https://bugs.openjdk.java.net/browse/JDK-7164841#comment-13384559).

The suffix should make finding the current GC log file quite a bit easier.

**Comment by ericbullen** [comment]
This is a part of a much bigger/uglier problem of jtune seeking back across log files that it does for analysis. Good that you pointed it out, but what you can do in the meantime is use the '--gc-stdin' option to cat in what logs/lines you want.

**Comment by kilink** [comment]
I don't see a '--gc-stdin' option.

It seems straightforward to at least fix the immediate issue using a glob like *.[0-9].current.  PR #14 may also fix the issue, but it probably does more work than necessary to find the ordering when the current log file is suffixed with .current.
