### ISSUE TITLE
JTune fails when run as root due to bug in jstat

### ISSUE THREAD

**Issue by kilink** [linkedin/JTune#18]
At some point, jstat/jps were broken in that they could not discover processes owned by other users when run as root. See [JDK-8075773](https://bugs.openjdk.java.net/browse/JDK-8075773), where it looks like the issue has been fixed.

However, it was somewhat difficult figuring out the cause when running JTune, since the failure would occur when accessing a nonexistent key in the jstat_data map.

I think it would be preferable to throw an exception when the return code from the subprocess call is non-zero. This might also warrant a mention in the documentation, since the FAQ says you can run JTune as root.

**Comment by ericbullen** [comment]
Makes sense, but I don't have the resources to make the change. If you want to do a pull request w/ the suggested changes, I can merge them in.
