### ISSUE TITLE
Not able to start jtune

### ISSUE THREAD

**Issue by sattishv** [linkedin/JTune#24]
Hi team,

Thanks for developing a great tool. But unfortunately we aren't able to use it because of a common mistake. We tried to resolve it but couldn't get through. have listed the error thrown. Could you please look into it

python jtune.py -h
  File "jtune.py", line 272
    return iter(subproc.stdout.readline, b'')
                                           ^
SyntaxError: invalid syntax

Thanks
Sattish.

**Comment by sattishv** [comment]
Hi team,

Sorry for the discommode. We identified the issue with regard to the error posted. It seems to be the old version we used 2.4 and the script worked as expected with version 2.7. This issue can be closed.

Thanks
Sattish.

**Comment by jesseward** [comment]
thanks @sattishv.  Closing this issue as per your previous comments.
