### ISSUE TITLE
Error trying to run it

### ISSUE THREAD

**Issue by yujikiriki** [linkedin/JTune#7]
When I execute jtune:

```
jtune.py -p 1234
```

This error occur: 
╰─✘ ./jtune.py --pid 13817
Traceback (most recent call last):
  File "./jtune.py", line 1899, in <module>
    proc_details = get_proc_info(cmd_args.pid)
  File "./jtune.py", line 1211, in get_proc_info
    gc_path = line.split(":", 1)[1]
IndexError: list index out of range

I am executing jtune on: 
+ Ubuntu 14.04 
+ Linux kernel 4.0.0 
+ Java version 1.8.0_25

**Comment by ericbullen** [comment]
Could you do a "ps auxww | grep <pid>", and "ls /proc/<pid>" as the same user that you ran jtune.py under? Thanks.

**Comment by yujikiriki** [comment]
ps auxww => https://gist.github.com/yujikiriki/988bb17ed0df7df03ea2
ls /proc => https://gist.github.com/yujikiriki/8b258aedfa0448ba6cfd

**Comment by ericbullen** [comment]
Markdown removed some of my text. Let's try this again:

```
Could you do a "ps auxww | grep <pid>", and "ls /proc/<pid>" as the same user that you ran jtune.py under? Thanks.
```

**Comment by yujikiriki** [comment]
np.

ps auxww | grep <pid>
```
yuji     19446  0.9  1.4 3520668 117328 pts/5  Sl+  17:41   0:03 /home/yuji/dev/jdk1.7.0_60/bin/java -jar git/certiarchivo/jar/certiarchivo-orquestador.jar -Xloggc -XX:+PrintTenuringDistribution -XX:+PrintGCDetails -XX:+PrintGCDateStamps
yuji     20027  0.0  0.0  15944  2180 pts/6    S+   17:47   0:00 grep --color 19446
```

ls /proc/
```
attr       clear_refs       cwd      fdinfo    maps       mountstats  oom_adj        personality  sessionid  statm    wchan
autogroup  cmdline          environ  io        mem        net         oom_score      root         smaps      status
auxv       comm             exe      limits    mountinfo  ns          oom_score_adj  sched        stack      syscall
cgroup     coredump_filter  fd       loginuid  mounts     numa_maps   pagemap        schedstat    stat       task
```

**Comment by ericbullen** [comment]
Looks like you need to specify the path to the gc log (via the -Xloggc:some/path). See here for more information:

http://docs.oracle.com/javase/6/docs/technotes/tools/windows/java.html

**Comment by yujikiriki** [comment]
My bad. 

Great tool!

Thanks.
