### ISSUE TITLE
JTune Mistakingly Thinks JVM is Running GC1, Java HotSpot 1.7.0_75"

### ISSUE THREAD

**Issue by kmasood** [linkedin/JTune#8]
Here are the `JAVA_OPTS`:

`java -Djava.util.logging.config.file=/app/apache/apache-tomcat-8.0.20/conf/logging.properties -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager -Xloggc:/app/apache/apache-tomcat-8.0.20/logs/gc.log -verbose:gc -XX:+PrintTenuringDistribution -XX:+PrintGCDetails -XX:+PrintGCDateStamps -Xmx2048m -Xms2048m -XX:MaxPermSize=1024m`

Output of jtune run: 

```
$ ./jtune.py -p $(pgrep -f tomcat)
Start Time:  2015-04-22 13:01:09.133616 GMT
Host:        tomcathost.example.com
2015-04-22 13:01:09,328: "root" (line: 1533) - ERROR Looks like you're running the G1 collector. This tool unfortunately doesn't currently support G1 analysis.
```

java -version:

```
$ ./java -version 
java version "1.7.0_75"
Java(TM) SE Runtime Environment (build 1.7.0_75-b13)
Java HotSpot(TM) 64-Bit Server VM (build 24.75-b04, mixed mode)
```

OS Oracle Enterprise Linux 6.6:

```
$ uname -a
Linux tomcathost.example.com 2.6.32-504.8.1.el6.x86_64 #1 SMP Tue Jan 27 12:21:41 PST 2015 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by ericbullen** [comment]
Can you output a few lines with headers of jstat for this process?

**Comment by kmasood** [comment]
Does something like this work? Lemme know if you need more information.

`$ ./jstat -gcutil $(pgrep -f tomcat) 250 7 `

|  S0  |   S1   |  E     | O     | P      |YGC    | YGCT |   FGC|  FGCT|   GCT|   
|------|--------|--------|-------|--------|-------|------|------|------|------|
| 61.25|   0.00 | 44.40  |82.33  |99.91   |1364   |32.090|     0| 0.000| 32.09|
| 61.25|   0.00 | 48.44  |82.33  |99.91   |1364   |32.090|     0| 0.000| 32.09|
| 61.25|   0.00 | 54.47  |82.33  |99.91   |1364   |32.090|     0| 0.000| 32.09|
| 61.25|   0.00 | 58.49  |82.33  |99.91   |1364   |32.090|     0| 0.000| 32.09|
| 61.25|   0.00 | 64.42  |82.33  |99.91   |1364   |32.090|     0| 0.000| 32.09|
| 61.25|   0.00 | 68.39  |82.33  |99.91   |1364   |32.090|     0| 0.000| 32.09|
| 61.25|   0.00 | 74.46  |82.33  |99.91   |1364   |32.090|     0| 0.000| 32.09|

**Comment by ericbullen** [comment]
not sure if there's a difference between -gcutil and -gc (what jtune uses). Can you use that option, and repost? Thanks.

**Comment by kmasood** [comment]
```
$ ./jstat -gc $(pgrep -f tomcat) 250 7 
 S0C    S1C    S0U    S1U      EC       EU        OC         OU       PC     PU    YGC     YGCT    FGC    FGCT     GCT   
2048.0 2048.0 1056.0  0.0   695296.0 83495.9  1398272.0   935195.8  145408.0 72509.7   1894   49.286   1      4.524   53.811
2048.0 2048.0 1056.0  0.0   695296.0 125269.4 1398272.0   935195.8  145408.0 72509.7   1894   49.286   1      4.524   53.811
2048.0 2048.0 1056.0  0.0   695296.0 153052.2 1398272.0   935195.8  145408.0 72509.7   1894   49.286   1      4.524   53.811
2048.0 2048.0 1056.0  0.0   695296.0 181032.6 1398272.0   935195.8  145408.0 72509.7   1894   49.286   1      4.524   53.811
2048.0 2048.0 1056.0  0.0   695296.0 208803.0 1398272.0   935195.8  145408.0 72509.7   1894   49.286   1      4.524   53.811
2048.0 2048.0 1056.0  0.0   695296.0 236798.6 1398272.0   935195.8  145408.0 72509.7   1894   49.286   1      4.524   53.811
2048.0 2048.0 1056.0  0.0   695296.0 264823.7 1398272.0   935195.8  145408.0 72509.7   1894   49.286   1      4.524   53.811
```

**Comment by kmasood** [comment]
For what it is worth, I'm occassionally get data, but it eventually errors out at line 1533, as noted in the first post.

```
$ ./jtune.py -p $(pgrep -f tomcat)  
#####
# Start Time:  2015-04-22 15:04:30.843613 GMT
# Host:        tomcat.example.com
#####
        EC      EP      EU  S0C/S1C     S0U     S1U      OC      OP      OU      PC     PU   YGC  YGCD  FGC  FGCD 
    ~~~~~~  ~~~~~~  ~~~~~~  ~~~~~~~  ~~~~~~  ~~~~~~  ~~~~~~  ~~~~~~  ~~~~~~  ~~~~~~  ~~~~~  ~~~~  ~~~~  ~~~  ~~~~ 
      675M   96.4%  650.7M       4M      2M      0K    1.3G   77.7%      1G    142M  70.9M  2246     -    1     - 
      675M   12.7%   86.1M       4M      0K    1.5M    1.3G   77.8%      1G    142M  70.9M  2247    +1    1     - 
      675M   27.0%  182.3M       4M      0K    1.5M    1.3G   77.8%      1G    142M  70.9M  2247     -    1     - 
      675M   36.5%  246.4M       4M      0K    1.5M    1.3G   77.8%      1G    142M  70.9M  2247     -    1     - 
      675M   52.2%  352.2M       4M      0K    1.5M    1.3G   77.8%      1G    142M  70.9M  2247     -    1     - 
      675M   64.9%    438M       4M      0K    1.5M    1.3G   77.8%      1G    142M  70.9M  2247     -    1     - 
      675M   78.5%    530M       4M      0K    1.5M    1.3G   77.8%      1G    142M  70.9M  2247     -    1     - 
      675M   92.9%  626.9M       4M      0K    1.5M    1.3G   77.8%      1G    142M  70.9M  2247     -    1     - 
      675M    6.9%   46.4M       4M    1.4M      0K    1.3G   77.9%      1G    142M  70.9M  2248    +1    1     - 
      675M   22.3%  150.8M       4M    1.4M      0K    1.3G   77.9%      1G    142M  70.9M  2248     -    1     - 
      675M   36.1%  243.8M       4M    1.4M      0K    1.3G   77.9%      1G    142M  70.9M  2248     -    1     - 
      675M   53.5%  360.9M       4M    1.4M      0K    1.3G   77.9%      1G    142M  70.9M  2248     -    1     - 
      675M   70.7%    477M       4M    1.4M      0K    1.3G   77.9%      1G    142M  70.9M  2248     -    1     - 
      675M   87.9%  593.4M       4M    1.4M      0K    1.3G   77.9%      1G    142M  70.9M  2248     -    1     - 
2015-04-22 15:04:45,090: "root" (line: 1533) - ERROR Looks like you're running the G1 collector. This tool unfortunately doesn't currently support G1 analysis. 
```

**Comment by ericbullen** [comment]
Interesting. So it reports the error while it's running, or after you hit ctrl-c?

**Comment by zodvik** [comment]
This happens for me as well.

`(line: 1528) - ERROR Looks like you're running the G1 collector. This tool unfortunately doesn't currently support G1 analysis.`

So, I added a line to print jstat data captured by the script by adding `print jstat_data` before `if jstat_data['S0C'][-1] == jstat_data['S1C'][-1]:`

This is the output
`{'YGC': [Decimal('79')], 'YGCT': [Decimal('0.501')], 'PC': [Decimal('46016')], 'YGCD': ['-'], 'OP': ['10.0%'], 'PU': [Decimal('46000')], 'OC': [Decimal('349568')], 'S0U': [Decimal('0')], 'EC': [Decimal('192384')], 'FGCT': [Decimal('0.000')], 'EU': [Decimal('3879')], 'GCT': [Decimal('0.501')], 'FGCD': ['-'], 'S1U': [Decimal('224')], 'S1C': [Decimal('256')], 'TIME_STAMP': [datetime.datetime(2015, 4, 23, 12, 22, 43, 946713)], 'OU': [Decimal('34853')], 'S0C': [Decimal('576')], 'EP': ['2.0%'], 'FGC': [Decimal('0')]}`

So, S0C != S1C.

**Comment by kmasood** [comment]
No, it reports the error during normal execution -- without any intervention.

Also, I can also confirm that by using `-XX:+UseConcMarkSweepGC `, the script runs fine; Tomcat 8, Java 7.

**Comment by ericbullen** [comment]
Thanks for the feedback everyone. I updated the code to make it more clear that the JVM needs to be using the CMS GC for this tool to work. Maybe some day in the future I'll add other GC options.
